export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'REMOVE_CATEGORY';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_NAV_CATEGORIESKEY = 'SET_NAV_CATEGORIESKEY';
export const NO_CATEGORIES = 'NO_CATEGORIES';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const REQUEST_NETWORK_ERROR = 'REQUEST_NETWORK_ERROR';