export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const SET_NAV_ADDRESSKEY = 'SET_NAV_ADDRESSKEY';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const NO_ADDRESS = 'NO_ADDRESS';
export const REQUEST_NETWORK_ERROR = 'REQUEST_NETWORK_ERROR';
