export const EDIT_PROFILE = 'EDIT_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_NAV_PROFILEKEY = 'SET_NAV_PROFILEKEY';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const REQUEST_NETWORK_ERROR = 'REQUEST_NETWORK_ERROR';
export const NO_PROFILE = 'NO_PROFILE';